services:
  - type: web
    name: sj-shop
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_TG_IDS
        sync: false
      - key: SHOP_URL
        sync: false
      - key: ADMIN_UPI_ID
        sync: false
      - key: ADMIN_UPI_NAME
        value: SJ Shop
